# window border
window.active.border.color: #807ad2
window.inactive.border.color: #9e6bc7

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #fd4663

# window titlebar background
window.active.title.bg.color: #807ad2
window.inactive.title.bg.color: #9e6bc7

window.active.label.text.color: #1b1b22
window.inactive.label.text.color: #19181f
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #272636

# window buttons
window.active.button.unpressed.image.color: #1b1b22
window.inactive.button.unpressed.image.color: #1b1b22

# menu
menu.border.color: #1b1b22
menu.items.bg.color: #807ad2
menu.items.text.color: #1b1b22
menu.items.active.bg.color: #9e6bc7
menu.items.active.text.color: #19181f
menu.separator.color: #1b1b22
menu.title.bg.color: #807ad2
menu.title.text.color: #1b1b22

# on screen display (window-cycle dialog)
osd.bg.color: #807ad2
osd.border.color: #1b1b22
osd.label.text.color: #1b1b22
osd.window-switcher.preview.border.color: #656575
